---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
        - name: cloudreach-docker-registry
      containers:
      - name: redis
        image: cloudreach/redis:{TAG}
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
